# Aliases shared across shells. Sourced from ~/.bashrc AFTER Omarchy's own
# aliases, so anything redefined here wins. Tab completion for the git ones is
# wired up in completions.sh -- keep the two files in sync.
#
# Names already taken by Omarchy (default/bash/aliases + fns/*) and avoided
# here: g gcm gcam gcad ga gd c cx cy d r t n ic ix icx mup ls lsa lt lta cd
# ff eff sff open.
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias dev='cd ~/Personal'
alias gaa='git add -A'
alias gap='git add -p'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit'
alias gcan='git commit --amend'
alias gcan!='git commit --amend --no-edit'
alias gco='git checkout'
alias gdc='git diff --cached'
alias gdf='git diff'
alias gfo='git fetch origin'
alias gfp='git push --force-with-lease'
alias gl='git log'
alias glg='git log --graph --oneline --decorate --all'
alias glo='git log --oneline'
alias gm='git merge'
alias gp='git push'
alias gr='git rebase'
alias grbom='git rebase origin/master'
alias grc='git rebase --continue'
alias grio='git rebase -i origin'
alias gst='git status'
alias gsta='git stash push'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsw='git switch'
alias gswc='git switch -c'
alias gt='git town'
alias gta='git town append'
alias gth='git town hack'
alias gtp='git town propose'
alias gts='git town sync'
alias hgrep='history | grep'
alias lg='lazygit'
alias ll='ls -lah'
alias path='echo -e "${PATH//:/\n}"'
alias ports='ss -tulpn'
alias reload='exec bash'
alias save='git add . && git commit -m'
alias ts='go-folder-finder run -backend fzf'
alias vi=nvim
alias vim=nvim
alias work='cd ~/Work'
